const canontraveldata = [
    {
        id: 1,
        no: 1,
        created_date: '2022-01-01',
        ca_no: 'CA001',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 10000,
        status: 'Approved',
        name: 'John Doe',
    },
    {
        id: 2,
        no: 2,
        created_date: '2022-01-01',
        ca_no: 'CA002',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 50000,
        status: 'Pending',
        name: 'Jane Smith',
    },
    {
        id: 3,
        no: 3,
        created_date: '2022-01-01',
        ca_no: 'CA003',
        event: 'Meeting',
        cost_center: 'CC001',
        nominal: 75000,
        status: 'Rejected',
        name: 'Bob Johnson',
    },
    {
        id: 4,
        no: 4,
        created_date: '2022-01-01',
        ca_no: 'CA004',
        event: 'Snack',
        cost_center: 'CC003',
        nominal: 25000,
        status: 'Approved',
        name: 'Alice Lee',
    },
    {
        id: 5,
        no: 5,
        created_date: '2022-01-01',
        ca_no: 'CA005',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 80000,
        status: 'Pending',
        name: 'David Brown',
    },
    {
        id: 6,
        no: 6,
        created_date: '2022-01-01',
        ca_no: 'CA006',
        event: 'Meeting',
        cost_center: 'CC003',
        nominal: 45000,
        status: 'Rejected',
        name: 'Samantha Johnson',
    },
    {
        id: 7,
        no: 7,
        created_date: '2022-01-01',
        ca_no: 'CA007',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 15000,
        status: 'Approved',
        name: 'Chris Green',
    },
    {
        id: 8,
        no: 8,
        created_date: '2022-01-01',
        ca_no: 'CA008',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 40000,
        status: 'Pending',
        name: 'Tom Wilson',
    },
    {
        id: 9,
        no: 9,
        created_date: '2022-01-01',
        ca_no: 'CA009',
        event: 'Meeting',
        cost_center: 'CC001',
        nominal: 50000,
        status: 'Rejected',
        name: 'Emily Davis',
    },
    {
        id: 10,
        no: 10,
        created_date: '2022-01-01',
        ca_no: 'CA010',
        event: 'Snack',
        cost_center: 'CC003',
        nominal: 20000,
        status: 'Approved',
        name: 'William Adams',
    },
    {
        id: 11,
        no: 11,
        created_date: '2022-01-01',
        ca_no: 'CA011',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 65000,
        status: 'Pending',
        name: 'Linda Jackson',
    },
    {
        id: 12,
        no: 12,
        created_date: '2022-01-01',
        ca_no: 'CA012',
        event: 'Meeting',
        cost_center: 'CC003',
        nominal: 35000,
        status: 'Rejected',
        name: 'Samuel Hernandez',
    },
    {
        id: 13,
        no: 13,
        created_date: '2022-01-01',
        ca_no: 'CA013',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 12000,
        status: 'Approved',
        name: 'Olivia Perez',
    },
    {
        id: 14,
        no: 14,
        created_date: '2022-01-01',
        ca_no: 'CA014',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 55000,
        status: 'Pending',
        name: 'Daniel Kim',
    },
    {
        id: 15,
        no: 15,
        created_date: '2022-01-01',
        ca_no: 'CA015',
        event: 'Meeting',
        cost_center: 'CC001',
        nominal: 30000,
        status: 'Rejected',
        name: 'Megan Chen',
    },
    {
        id: 16,
        no: 16,
        created_date: '2022-01-01',
        ca_no: 'CA016',
        event: 'Snack',
        cost_center: 'CC003',
        nominal: 18000,
        status: 'Approved',
        name: 'Benjamin Garcia',
    },
    {
        id: 17,
        no: 17,
        created_date: '2022-01-01',
        ca_no: 'CA017',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 45000,
        status: 'Pending',
        name: 'Sophia Kim',
    },
    {
        id: 18,
        no: 18,
        created_date: '2022-01-01',
        ca_no: 'CA018',
        event: 'Meeting',
        cost_center: 'CC003',
        nominal: 25000,
        status: 'Rejected',
        name: 'Christopher Lee',
    },
    {
        id: 19,
        no: 19,
        created_date: '2022-01-01',
        ca_no: 'CA019',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 8000,
        status: 'Approved',
        name: 'Isabella Hernandez',
    },
    {
        id: 20,
        no: 20,
        created_date: '2022-01-01',
        ca_no: 'CA020',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 35000,
        status: 'Pending',
        name: 'Ethan Johnson',
    },
    {
        id: 21,
        no: 21,
        created_date: '2022-01-01',
        ca_no: 'CA021',
        event: 'Meeting',
        cost_center: 'CC003',
        nominal: 15000,
        status: 'Rejected',
        name: 'Madison Davis',
    },
    {
        id: 22,
        no: 22,
        created_date: '2022-01-01',
        ca_no: 'CA022',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 13000,
        status: 'Approved',
        name: 'Alexander Brown',
    },
    {
        id: 23,
        no: 23,
        created_date: '2022-01-01',
        ca_no: 'CA023',
        event: 'Sport',
        cost_center: 'CC002',
        nominal: 60000,
        status: 'Pending',
        name: 'Ava Jackson',
    },
    {
        id: 24,
        no: 24,
        created_date: '2022-01-01',
        ca_no: 'CA024',
        event: 'Meeting',
        cost_center: 'CC003',
        nominal: 40000,
        status: 'Rejected',
        name: 'Braitwaite',
    },
    {
        id: 25,
        no: 25,
        created_date: '2022-01-01',
        ca_no: 'CA025',
        event: 'Snack',
        cost_center: 'CC001',
        nominal: 11000,
        status: 'Approved',
        name: 'Steven G',
    }
];

export default canontraveldata;