const carData = [
    { id: 1, plat_number: "B 1234 ABC", company: "PT. Aneka Jaya", site: "Site A" },
    { id: 2, plat_number: "B 2345 BCD", company: "PT. Mega Sentosa", site: "Site B" },
    { id: 3, plat_number: "B 3456 CDE", company: "PT. Sejahtera Abadi", site: "Site C" },
    { id: 4, plat_number: "B 4567 DEF", company: "PT. Sukses Mandiri", site: "Site D" },
    { id: 5, plat_number: "B 5678 EFG", company: "PT. Berkat Jaya", site: "Site E" },
    { id: 6, plat_number: "B 6789 FGH", company: "PT. Cipta Sentosa", site: "Site F" },
    { id: 7, plat_number: "B 7890 GHI", company: "PT. Maju Jaya", site: "Site G" },
    { id: 8, plat_number: "B 8901 HIJ", company: "PT. Abadi Sentosa", site: "Site H" },
    { id: 9, plat_number: "B 9012 IJK", company: "PT. Makmur Jaya", site: "Site I" },
    { id: 10, plat_number: "B 0123 JKL", company: "PT. Sejahtera Makmur", site: "Site J" },
    { id: 11, plat_number: "B 2346 KLM", company: "PT. Sukses Abadi", site: "Site A" },
    { id: 12, plat_number: "B 3457 LMN", company: "PT. Jaya Makmur", site: "Site B" },
    { id: 13, plat_number: "B 4568 MNO", company: "PT. Sentosa Abadi", site: "Site C" },
    { id: 14, plat_number: "B 5679 NOP", company: "PT. Maju Makmur", site: "Site D" },
    { id: 15, plat_number: "B 6780 OPQ", company: "PT. Abadi Jaya", site: "Site E" },
    { id: 16, plat_number: "B 7891 PQR", company: "PT. Berkat Sentosa", site: "Site F" },
    { id: 17, plat_number: "B 8902 QRS", company: "PT. Cipta Makmur", site: "Site G" },
    { id: 18, plat_number: "B 9013 RST", company: "PT. Sukses Jaya", site: "Site H" },
    { id: 19, plat_number: "B 0124 STU", company: "PT. Makmur Sentosa", site: "Site I" },
    { id: 20, plat_number: "B 2347 TUV", company: "PT. Sejahtera Abadi", site: "Site J" },
    { id: 21, plat_number: "B 3458 UVW", company: "PT. Sukses Makmur", site: "Site K" },
    { id: 22, plat_number: "B 3459 WXY", company: "PT. Jalan Bareng Jadian Kaga", site: "Site L" },
    { id: 23, plat_number: "B 3456 ZAB", company: "PT. Maju Kena Mundur Kena", site: "Site M" },
    { id: 24, plat_number: "B 7890 ABC", company: "PT. Angin Ribut", site: "Site N" },
    { id: 25, plat_number: "B 6789 DEF", company: "PT. Pencari Cinta Sejati", site: "Site O" },
]

export default carData;