const dataCompany = [
    {
        id: 1,
        code: 'ACME',
        name: 'ACME Corporation',
        parent: null,
    },
    {
        id: 2,
        code: 'ABC',
        name: 'ABC Corporation',
        parent: null,
    },
    {
        id: 3,
        code: 'DEF',
        name: 'DEF Enterprises',
        parent: null,
    },
    {
        id: 4,
        code: 'GHI',
        name: 'GHI Industries',
        parent: null,
    },
    {
        id: 5,
        code: 'JKL',
        name: 'JKL Corporation',
        parent: null,
    },
    {
        id: 6,
        code: 'MNO',
        name: 'MNO Enterprises',
        parent: null,
    },
    {
        id: 7,
        code: 'PQR',
        name: 'PQR Industries',
        parent: null,
    },
    {
        id: 8,
        code: 'STU',
        name: 'STU Corporation',
        parent: null,
    },
    {
        id: 9,
        code: 'VWX',
        name: 'VWX Enterprises',
        parent: null,
    },
    {
        id: 10,
        code: 'YZA',
        name: 'YZA Industries',
        parent: null,
    },
    {
        id: 11,
        code: 'ACME-001',
        name: 'ACME Subsidiary 1',
        parent: 'ACME',
    },
    {
        id: 12,
        code: 'ACME-002',
        name: 'ACME Subsidiary 2',
        parent: 'ACME',
    },
    {
        id: 13,
        code: 'ABC-001',
        name: 'ABC Subsidiary 1',
        parent: 'ABC',
    },
    {
        id: 14,
        code: 'ABC-002',
        name: 'ABC Subsidiary 2',
        parent: 'ABC',
    },
    {
        id: 15,
        code: 'DEF-001',
        name: 'DEF Subsidiary 1',
        parent: 'DEF',
    },
    {
        id: 16,
        code: 'DEF-002',
        name: 'DEF Subsidiary 2',
        parent: 'DEF',
    },
    {
        id: 17,
        code: 'GHI-001',
        name: 'GHI Subsidiary 1',
        parent: 'GHI',
    },
    {
        id: 18,
        code: 'GHI-002',
        name: 'GHI Subsidiary 2',
        parent: 'GHI',
    },
    {
        id: 19,
        code: 'JKL-001',
        name: 'JKL Subsidiary 1',
        parent: 'JKL',
    },
    {
        id: 20,
        code: 'JKL-002',
        name: 'JKL Subsidiary 2',
        parent: 'JKL',
    },
    {
        id: 21,
        code: 'MNO-001',
        name: 'MNO Subsidiary 1',
        parent: 'MNO',
    },
    {
        id: 22,
        code: 'DEF-007',
        name: 'DEF Defensive 1',
        parent: 'BGR',
    },
    {
        id: 23,
        code: 'ATK-011',
        name: 'ATK Craft Zero',
        parent: 'ACZ',
    },
    {
        id: 24,
        code: 'SLK-004',
        name: 'SLK Automata 10',
        parent: 'SYZ',
    },
    {
        id: 25,
        code: 'SZA-K1L',
        name: 'SZA KILL ONE',
        parent: 'SZA',
    },
]

export default dataCompany;
