const departementData = [
    {
        id: 1,
        name_departement: 'Keuangan',
        cost_center: 'CC001',
        status: 'Aktif',
        name_departement_head: 'Budi',
    },
    {
        id: 2,
        name_departement: 'Pemasaran',
        cost_center: 'CC002',
        status: 'Aktif',
        name_departement_head: 'Siti',
    },
    {
        id: 3,
        name_departement: 'Teknologi Informasi',
        cost_center: 'CC003',
        status: 'Tidak Aktif',
        name_departement_head: 'Andi',
    },
    {
        id: 4,
        name_departement: 'Sumber Daya Manusia',
        cost_center: 'CC004',
        status: 'Aktif',
        name_departement_head: 'Rini',
    },
    {
        id: 5,
        name_departement: 'Pengadaan',
        cost_center: 'CC005',
        status: 'Tidak Aktif',
        name_departement_head: 'Dedi',
    },
    {
        id: 6,
        name_departement: 'Operasional',
        cost_center: 'CC006',
        status: 'Aktif',
        name_departement_head: 'Aldi',
    },
    {
        id: 7,
        name_departement: 'Penjualan',
        cost_center: 'CC007',
        status: 'Aktif',
        name_departement_head: 'Wulan',
    },
    {
        id: 8,
        name_departement: 'Manufaktur',
        cost_center: 'CC008',
        status: 'Tidak Aktif',
        name_departement_head: 'Ari',
    },
    {
        id: 9,
        name_departement: 'Perencanaan',
        cost_center: 'CC009',
        status: 'Aktif',
        name_departement_head: 'Dian',
    },
    {
        id: 10,
        name_departement: 'Kualitas',
        cost_center: 'CC010',
        status: 'Aktif',
        name_departement_head: 'Fahri',
    },
    {
        id: 11,
        name_departement: 'Pelayanan Pelanggan',
        cost_center: 'CC011',
        status: 'Tidak Aktif',
        name_departement_head: 'Bima',
    },
    {
        id: 12,
        name_departement: 'Hubungan Masyarakat',
        cost_center: 'CC012',
        status: 'Aktif',
        name_departement_head: 'Sari',
    },
    {
        id: 13,
        name_departement: 'Logistik',
        cost_center: 'CC013',
        status: 'Aktif',
        name_departement_head: 'Eka',
    },
    {
        id: 14,
        name_departement: 'Riset dan Pengembangan',
        cost_center: 'CC014',
        status: 'Tidak Aktif',
        name_departement_head: 'Gita',
    },
    {
        id: 15,
        name_departement: 'Produksi',
        cost_center: 'CC015',
        status: 'Aktif',
        name_departement_head: 'Firman',
    },
    {
        id: 16,
        name_departement: 'Pemeliharaan',
        cost_center: 'CC016',
        status: 'Aktif',
        name_departement_head: 'Indah',
    },
    {
        id: 17,
        name_departement: 'Penjaminan Mutu',
        cost_center: 'CC017',
        status: 'Aktif',
        name_departement_head: 'Bella',
    },
    {
        id: 18,
        name_departement: 'Pengembangan Produk',
        cost_center: 'CC018',
        status: 'Tidak Aktif',
        name_departement_head: 'Cahyo',
    },
    {
        id: 19,
        name_departement: 'Pengawasan Operasional',
        cost_center: 'CC019',
        status: 'Aktif',
        name_departement_head: 'Dinda',
    },
    {
        id: 20,
        name_departement: 'Pengembangan Bisnis',
        cost_center: 'CC020',
        status: 'Aktif',
        name_departement_head: 'Evan',
    },
    {
        id: 21,
        name_departement: 'Akuntansi',
        cost_center: 'CC021',
        status: 'Tidak Aktif',
        name_departement_head: 'Fina',
    },
    {
        id: 22,
        name_departement: 'Pengolahan Data',
        cost_center: 'CC022',
        status: 'Aktif',
        name_departement_head: 'Gina',
    },
    {
        id: 23,
        name_departement: 'Pengembangan Sistem',
        cost_center: 'CC023',
        status: 'Aktif',
        name_departement_head: 'Hadi',
    },
    {
        id: 24,
        name_departement: 'Perizinan',
        cost_center: 'CC024',
        status: 'Tidak Aktif',
        name_departement_head: 'Ivan',
    },
    {
        id: 25,
        name_departement: 'Pengamanan',
        cost_center: 'CC025',
        status: 'Aktif',
        name_departement_head: 'Jaka',
    },
]

export default departementData;