const departementData = [
    {
        id: 1,
        no: 1,
        name_departement: 'Keuangan',
        cost_center: 'CC001',
        status: 'Aktif',
        name_departement_head: 'Budi',
        company: "PT. Aneka Jaya",
    },
    {
        id: 2,
        no: 2,
        name_departement: 'Pemasaran',
        cost_center: 'CC002',
        status: 'Aktif',
        name_departement_head: 'Siti',
        company: "PT. Mega Sentosa",
    },
    {
        id: 3,
        no: 3,
        name_departement: 'Teknologi Informasi',
        cost_center: 'CC003',
        status: 'Tidak Aktif',
        name_departement_head: 'Andi',
        company: "PT. Sejahtera Abadi",
    },
    {
        id: 4,
        no: 4,
        name_departement: 'Sumber Daya Manusia',
        cost_center: 'CC004',
        status: 'Aktif',
        name_departement_head: 'Rini',
        company: "PT. Sukses Mandiri",
    },
    {
        id: 5,
        no: 5,
        name_departement: 'Pengadaan',
        cost_center: 'CC005',
        status: 'Tidak Aktif',
        name_departement_head: 'Dedi',
        company: "PT. Berkat Jaya",
    },
    {
        id: 6,
        no: 6,
        name_departement: 'Operasional',
        cost_center: 'CC006',
        status: 'Aktif',
        name_departement_head: 'Aldi',
        company: "PT. Cipta Sentosa",
    },
    {
        id: 7,
        no: 7,
        name_departement: 'Penjualan',
        cost_center: 'CC007',
        status: 'Aktif',
        name_departement_head: 'Wulan',
        company: "PT. Maju Jaya",
    },
    {
        id: 8,
        no: 8,
        name_departement: 'Manufaktur',
        cost_center: 'CC008',
        status: 'Tidak Aktif',
        name_departement_head: 'Ari',
        company: "PT. Abadi Sentosa",
    },
    {
        id: 9,
        no: 9,
        name_departement: 'Perencanaan',
        cost_center: 'CC009',
        status: 'Aktif',
        name_departement_head: 'Dian',
        company: "PT. Makmur Jaya",
    },
    {
        id: 10,
        no: 10,
        name_departement: 'Kualitas',
        cost_center: 'CC010',
        status: 'Aktif',
        name_departement_head: 'Fahri',
        company: "PT. Sejahtera Makmur",
    },
    {
        id: 11,
        no: 11,
        name_departement: 'Pelayanan Pelanggan',
        cost_center: 'CC011',
        status: 'Tidak Aktif',
        name_departement_head: 'Bima',
        company: "PT. Sukses Abadi",
    },
    {
        id: 12,
        no: 12,
        name_departement: 'Hubungan Masyarakat',
        cost_center: 'CC012',
        status: 'Aktif',
        name_departement_head: 'Sari',
        company: "PT. Jaya Makmur",
    },
    {
        id: 13,
        no: 13,
        name_departement: 'Logistik',
        cost_center: 'CC013',
        status: 'Aktif',
        name_departement_head: 'Eka',
        company: "PT. Sentosa Abadi",
    },
    {
        id: 14,
        no: 14,
        name_departement: 'Riset dan Pengembangan',
        cost_center: 'CC014',
        status: 'Tidak Aktif',
        name_departement_head: 'Gita',
        company: "PT. Maju Makmur",
    },
    {
        id: 15,
        no: 15,
        name_departement: 'Produksi',
        cost_center: 'CC015',
        status: 'Aktif',
        name_departement_head: 'Firman',
        company: "PT. Abadi Jaya",
    },
    {
        id: 16,
        no: 16,
        name_departement: 'Pemeliharaan',
        cost_center: 'CC016',
        status: 'Aktif',
        name_departement_head: 'Indah',
        company: "PT. Berkat Sentosa",
    },
    {
        id: 17,
        no: 17,
        name_departement: 'Penjaminan Mutu',
        cost_center: 'CC017',
        status: 'Aktif',
        name_departement_head: 'Bella',
        company: "PT. Cipta Makmur",
    },
    {
        id: 18,
        no: 18,
        name_departement: 'Pengembangan Produk',
        cost_center: 'CC018',
        status: 'Tidak Aktif',
        name_departement_head: 'Cahyo',
        company: "PT. Sukses Jaya",
    },
    {
        id: 19,
        no: 19,
        name_departement: 'Pengawasan Operasional',
        cost_center: 'CC019',
        status: 'Aktif',
        name_departement_head: 'Dinda',
        company: "PT. Makmur Sentosa",
    },
    {
        id: 20,
        no: 20,
        name_departement: 'Pengembangan Bisnis',
        cost_center: 'CC020',
        status: 'Aktif',
        name_departement_head: 'Evan',
        company: "PT. Sejahtera Abadi",
    },
    {
        id: 21,
        no: 21,
        name_departement: 'Akuntansi',
        cost_center: 'CC021',
        status: 'Tidak Aktif',
        name_departement_head: 'Fina',
        company: "PT. Sukses Makmur",
    },
    {
        id: 22,
        no: 22,
        name_departement: 'Pengolahan Data',
        cost_center: 'CC022',
        status: 'Aktif',
        name_departement_head: 'Gina',
        company: "PT. Jalan Bareng Jadian Kaga",
    },
    {
        id: 23,
        no: 23,
        name_departement: 'Pengembangan Sistem',
        cost_center: 'CC023',
        status: 'Aktif',
        name_departement_head: 'Hadi',
        company: "PT. Maju Kena Mundur Kena",
    },
    {
        id: 24,
        no: 24,
        name_departement: 'Perizinan',
        cost_center: 'CC024',
        status: 'Tidak Aktif',
        name_departement_head: 'Ivan',
        company: "PT. Angin Ribut",
    },
    {
        id: 25,
        no: 25,
        name_departement: 'Pengamanan',
        cost_center: 'CC025',
        status: 'Aktif',
        name_departement_head: 'Jaka',
        company: "PT. Pencari Cinta Sejati",
    },
]

export default departementData;