const employeeData = [
    {
        id: 1,
        sn: "A001",
        name: "John Doe",
        gender: "Male",
        email: "johndoe@gmail.com",
        phone_number: "08123456789",
    },
    {
        id: 2,
        sn: "A002",
        name: "Jane Doe",
        gender: "Female",
        email: "janedoe@gmail.com",
        phone_number: "08123456790",
    },
    {
        id: 3,
        sn: "A003",
        name: "David",
        gender: "Male",
        email: "david@gmail.com",
        phone_number: "08123456791",
    },
    {
        id: 4,
        sn: "A004",
        name: "Samantha",
        gender: "Female",
        email: "samantha@gmail.com",
        phone_number: "08123456792",
    },
    {
        id: 5,
        sn: "A005",
        name: "Michael",
        gender: "Male",
        email: "michael@gmail.com",
        phone_number: "08123456793",
    },
    {
        id: 6,
        sn: "A006",
        name: "Sophie",
        gender: "Female",
        email: "sophie@gmail.com",
        phone_number: "08123456794",
    },
    {
        id: 7,
        sn: "A007",
        name: "Adam",
        gender: "Male",
        email: "adam@gmail.com",
        phone_number: "08123456795",
    },
    {
        id: 8,
        sn: "A008",
        name: "Emma",
        gender: "Female",
        email: "emma@gmail.com",
        phone_number: "08123456796",
    },
    {
        id: 9,
        sn: "A009",
        name: "Daniel",
        gender: "Male",
        email: "daniel@gmail.com",
        phone_number: "08123456797",
    },
    {
        id: 10,
        sn: "A010",
        name: "Olivia",
        gender: "Female",
        email: "olivia@gmail.com",
        phone_number: "08123456798",
    },
    {
        id: 11,
        sn: "A011",
        name: "William",
        gender: "Male",
        email: "william@gmail.com",
        phone_number: "08123456799",
    },
    {
        id: 12,
        sn: "A012",
        name: "Ava",
        gender: "Female",
        email: "ava@gmail.com",
        phone_number: "08123456800",
    },
    {
        id: 13,
        sn: "A013",
        name: "Joshua",
        gender: "Male",
        email: "joshua@gmail.com",
        phone_number: "08123456801",
    },
    {
        id: 14,
        sn: "A014",
        name: "Isabella",
        gender: "Female",
        email: "isabella@gmail.com",
        phone_number: "08123456802",
    },
    {
        id: 15,
        sn: "A015",
        name: "Christopher",
        gender: "Male",
        email: "christopher@gmail.com",
        phone_number: "08123456803"
    },
    {
        id: 16,
        sn: "A016",
        name: "Ella",
        gender: "Female",
        email: "ella@gmail.com",
        phone_number: "08123456803",
    },
    {
        id: 17,
        sn: "A017",
        name: "Andrew",
        gender: "Male",
        email: "andrew@gmail.com",
        phone_number: "08123456804",
    },
    {
        id: 18,
        sn: "A018",
        name: "Abigail",
        gender: "Female",
        email: "abigail@gmail.com",
        phone_number: "08123456805",
    },
    {
        id: 19,
        sn: "A019",
        name: "Ethan",
        gender: "Male",
        email: "ethan@gmail.com",
        phone_number: "08123456806",
    },
    {
        id: 20,
        sn: "A020",
        name: "Sophia",
        gender: "Female",
        email: "sophia@gmail.com",
        phone_number: "08123456807",
    },
    {
        id: 21,
        sn: "A021",
        name: "James",
        gender: "Male",
        email: "james@gmail.com",
        phone_number: "08123456808",
    },
    {
        id: 22,
        sn: "A022",
        name: "Chloe",
        gender: "Female",
        email: "chloe@gmail.com",
        phone_number: "08123456809",
    },
    {
        id: 23,
        sn: "A023",
        name: "Joseph",
        gender: "Male",
        email: "joseph@gmail.com",
        phone_number: "08123456810",
    },
    {
        id: 24,
        sn: "A024",
        name: "Madison",
        gender: "Female",
        email: "madison@gmail.com",
        phone_number: "08123456811",
    },
    {
        id: 25,
        sn: "A025",
        name: "Benjamin",
        gender: "Male",
        email: "benjamin@gmail.com",
        phone_number: "08123456812",
    },
]

export default employeeData
