const employeeData = [
    {
        id: 1,
        no: 1,
        sn: "A001",
        name: "John Doe",
        gender: "Male",
        email: "johndoe@gmail.com",
        phone_number: "08123456789",
        company: "PT. Aneka Jaya",
    },
    {
        id: 2,
        no: 2,
        sn: "A002",
        name: "Jane Doe",
        gender: "Female",
        email: "janedoe@gmail.com",
        phone_number: "08123456790",
        company: "PT. Mega Sentosa",
    },
    {
        id: 3,
        no: 3,
        sn: "A003",
        name: "David",
        gender: "Male",
        email: "david@gmail.com",
        phone_number: "08123456791",
        company: "PT. Sejahtera Abadi",
    },
    {
        id: 4,
        no: 4,
        sn: "A004",
        name: "Samantha",
        gender: "Female",
        email: "samantha@gmail.com",
        phone_number: "08123456792",
        company: "PT. Sukses Mandiri",
    },
    {
        id: 5,
        no: 5,
        sn: "A005",
        name: "Michael",
        gender: "Male",
        email: "michael@gmail.com",
        phone_number: "08123456793",
        company: "PT. Berkat Jaya",
    },
    {
        id: 6,
        no: 6,
        sn: "A006",
        name: "Sophie",
        gender: "Female",
        email: "sophie@gmail.com",
        phone_number: "08123456794",
        company: "PT. Cipta Sentosa",
    },
    {
        id: 7,
        no: 7,
        sn: "A007",
        name: "Adam",
        gender: "Male",
        email: "adam@gmail.com",
        phone_number: "08123456795",
        company: "PT. Maju Jaya",
    },
    {
        id: 8,
        no: 8,
        sn: "A008",
        name: "Emma",
        gender: "Female",
        email: "emma@gmail.com",
        phone_number: "08123456796",
        company: "PT. Abadi Sentosa",
    },
    {
        id: 9,
        no: 9,
        sn: "A009",
        name: "Daniel",
        gender: "Male",
        email: "daniel@gmail.com",
        phone_number: "08123456797",
        company: "PT. Makmur Jaya",
    },
    {
        id: 10,
        no: 10,
        sn: "A010",
        name: "Olivia",
        gender: "Female",
        email: "olivia@gmail.com",
        phone_number: "08123456798",
        company: "PT. Sejahtera Makmur",
    },
    {
        id: 11,
        no: 11,
        sn: "A011",
        name: "William",
        gender: "Male",
        email: "william@gmail.com",
        phone_number: "08123456799",
        company: "PT. Sukses Abadi",
    },
    {
        id: 12,
        no: 12,
        sn: "A012",
        name: "Ava",
        gender: "Female",
        email: "ava@gmail.com",
        phone_number: "08123456800",
        company: "PT. Jaya Makmur",
    },
    {
        id: 13,
        no: 13,
        sn: "A013",
        name: "Joshua",
        gender: "Male",
        email: "joshua@gmail.com",
        phone_number: "08123456801",
        company: "PT. Sentosa Abadi",
    },
    {
        id: 14,
        no: 14,
        sn: "A014",
        name: "Isabella",
        gender: "Female",
        email: "isabella@gmail.com",
        phone_number: "08123456802",
        company: "PT. Maju Makmur",
    },
    {
        id: 15,
        no: 15,
        sn: "A015",
        name: "Christopher",
        gender: "Male",
        email: "christopher@gmail.com",
        phone_number: "08123456803",
        company: "PT. Abadi Jaya",
    },
    {
        id: 16,
        no: 16,
        sn: "A016",
        name: "Ella",
        gender: "Female",
        email: "ella@gmail.com",
        phone_number: "08123456803",
        company: "PT. Berkat Sentosa",
    },
    {
        id: 17,
        no: 17,
        sn: "A017",
        name: "Andrew",
        gender: "Male",
        email: "andrew@gmail.com",
        phone_number: "08123456804",
        company: "PT. Cipta Makmur",
    },
    {
        id: 18,
        no: 18,
        sn: "A018",
        name: "Abigail",
        gender: "Female",
        email: "abigail@gmail.com",
        phone_number: "08123456805",
        company: "PT. Sukses Jaya",
    },
    {
        id: 19,
        no: 19,
        sn: "A019",
        name: "Ethan",
        gender: "Male",
        email: "ethan@gmail.com",
        phone_number: "08123456806",
        company: "PT. Makmur Sentosa",
    },
    {
        id: 20,
        no: 20,
        sn: "A020",
        name: "Sophia",
        gender: "Female",
        email: "sophia@gmail.com",
        phone_number: "08123456807",
        company: "PT. Sejahtera Abadi",
    },
    {
        id: 21,
        no: 21,
        sn: "A021",
        name: "James",
        gender: "Male",
        email: "james@gmail.com",
        phone_number: "08123456808",
        company: "PT. Sukses Makmur",
    },
    {
        id: 22,
        no: 22,
        sn: "A022",
        name: "Chloe",
        gender: "Female",
        email: "chloe@gmail.com",
        phone_number: "08123456809",
        company: "PT. Jalan Bareng Jadian Kaga",
    },
    {
        id: 23,
        no: 23,
        sn: "A023",
        name: "Joseph",
        gender: "Male",
        email: "joseph@gmail.com",
        phone_number: "08123456810",
        company: "PT. Maju Kena Mundur Kena",
    },
    {
        id: 24,
        no: 24,
        sn: "A024",
        name: "Madison",
        gender: "Female",
        email: "madison@gmail.com",
        phone_number: "08123456811",
        company: "PT. Angin Ribut",
    },
    {
        id: 25,
        no: 25,
        sn: "A025",
        name: "Benjamin",
        gender: "Male",
        email: "benjamin@gmail.com",
        phone_number: "08123456812",
        company: "PT. Pencari Cinta Sejati",
    },
]

export default employeeData
