const flightData = [
    { id: 1, no: 1, flight_class: "Economy" },
    { id: 2, no: 2, flight_class: "Business" },
    { id: 3, no: 3, flight_class: "First Class" },
    { id: 4, no: 4, flight_class: "Economy" },
    { id: 5, no: 5, flight_class: "Business" },
    { id: 6, no: 6, flight_class: "First Class" },
    { id: 7, no: 7, flight_class: "Economy" },
    { id: 8, no: 8, flight_class: "Business" },
    { id: 9, no: 9, flight_class: "First Class" },
    { id: 10, no: 10, flight_class: "Economy" },
    { id: 11, no: 11, flight_class: "Business" },
    { id: 12, no: 12, flight_class: "First Class" },
    { id: 13, no: 13, flight_class: "Economy" },
    { id: 14, no: 14, flight_class: "Business" },
    { id: 15, no: 15, flight_class: "First Class" },
    { id: 16, no: 16, flight_class: "Economy" },
    { id: 17, no: 17, flight_class: "Business" },
    { id: 18, no: 18, flight_class: "First Class" },
    { id: 19, no: 19, flight_class: "Economy" },
    { id: 20, no: 20, flight_class: "Business" },
    { id: 21, no: 21, flight_class: "First Class" },
    { id: 22, no: 22, flight_class: "Economy" },
    { id: 23, no: 23, flight_class: "Business" },
    { id: 24, no: 24, flight_class: "First Class" },
    { id: 25, no: 25, flight_class: "Economy" },
]

export default flightData