const flightData = [
    { id: 1, flight_class: "Economy" },
    { id: 2, flight_class: "Business" },
    { id: 3, flight_class: "First Class" },
    { id: 4, flight_class: "Economy" },
    { id: 5, flight_class: "Business" },
    { id: 6, flight_class: "First Class" },
    { id: 7, flight_class: "Economy" },
    { id: 8, flight_class: "Business" },
    { id: 9, flight_class: "First Class" },
    { id: 10, flight_class: "Economy" },
    { id: 11, flight_class: "Business" },
    { id: 12, flight_class: "First Class" },
    { id: 13, flight_class: "Economy" },
    { id: 14, flight_class: "Business" },
    { id: 15, flight_class: "First Class" },
    { id: 16, flight_class: "Economy" },
    { id: 17, flight_class: "Business" },
    { id: 18, flight_class: "First Class" },
    { id: 19, flight_class: "Economy" },
    { id: 20, flight_class: "Business" },
    { id: 21, flight_class: "First Class" },
    { id: 22, flight_class: "Economy" },
    { id: 23, flight_class: "Business" },
    { id: 24, flight_class: "First Class" },
    { id: 25, flight_class: "Economy" },
]

export default flightData