const atkrequestdata = [
    {
        id: 1,
        no: 1,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/18596/03.2023",
        requestor: "John Doe",
        id_item: "ID-1234",
        name_item: "Pen",
        quantity: 5,
        status: "Claim has been requested by John Doe",
        status_type: "Pending"
    },
    {
        id: 2,
        no: 2,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/20541/03.2023",
        requestor: "Jane Smith",
        id_item: "ID-5678",
        name_item: "Pencil",
        quantity: 10,
        status: "Claim has been requested by Jane Smith",
        status_type: "Pending"
    },
    {
        id: 3,
        no: 3,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/30567/03.2023",
        requestor: "Bob Johnson",
        id_item: "ID-9101",
        name_item: "Paper",
        quantity: 20,
        status: "Claim has been requested by Bob Johnson",
        status_type: "Pending"
    },
    {
        id: 4,
        no: 4,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/40123/03.2023",
        requestor: "Lisa Brown",
        id_item: "ID-1213",
        name_item: "Book",
        quantity: 2,
        status: "Claim has been requested by Lisa Brown",
        status_type: "Pending"
    },
    {
        id: 5,
        no: 5,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/50678/03.2023",
        requestor: "Tom Wilson",
        id_item: "ID-1415",
        name_item: "Eraser",
        quantity: 3,
        status: "Claim has been requested by Tom Wilson",
        status_type: "Pending"
    },
    {
        id: 6,
        no: 6,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/60234/03.2023",
        requestor: "Karen Davis",
        id_item: "ID-1617",
        name_item: "Highlighter",
        quantity: 8,
        status: "Claim has been requested by Karen Davis",
        status_type: "Pending"
    },
    {
        id: 7,
        no: 7,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/70589/03.2023",
        requestor: "Mike Clark",
        id_item: "ID-1819",
        name_item: "Stapler",
        quantity: 1,
        status: "Claim has been requested by Mike Clark",
        status_type: "Pending"
    },
    {
        id: 8,
        no: 8,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/80235/03.2023",
        requestor: "Samantha Lee",
        id_item: "ID-2021",
        name_item: "Scissors",
        quantity: 2,
        status: "Claim has been requested by Samantha Lee",
        status_type: "Pending"
    },
    {
        id: 9,
        no: 9,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/90580/03.2023",
        requestor: "David Rodriguez",
        id_item: "ID-2223",
        name_item: "Folder",
        quantity: 6,
        status: "Claim has been requested by David Rodriguez",
        status_type: "Pending"
    },
    {
        id: 10,
        no: 10,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/100926/03.2023",
        requestor: "Jessica Martinez",
        id_item: "ID-2425",
        name_item: "Ruler",
        quantity: 1,
        status: "Claim has been requested by Jessica Martinez",
        status_type: "Pending"
    },
    {
        id: 11,
        no: 11,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/110571/03.2023",
        requestor: "Michael Brown",
        id_item: "ID-2627",
        name_item: "Notebook",
        quantity: 3,
        status: "Claim has been requested by Michael Brown",
        status_type: "Pending"
    },
    {
        id: 12,
        no: 12,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/120216/03.2023",
        requestor: "Jennifer Taylor",
        id_item: "ID-2829",
        name_item: "Markers",
        quantity: 8,
        status: "Claim has been requested by Jennifer Taylor",
        status_type: "Pending"
    },
    {
        id: 13,
        no: 13,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/130861/03.2023",
        requestor: "Christopher Johnson",
        id_item: "ID-3031",
        name_item: "Correction tape",
        quantity: 2,
        status: "Claim has been requested by Christopher Johnson",
        status_type: "Pending"
    },
    {
        id: 14,
        no: 14,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/140506/03.2023",
        requestor: "Amanda Davis",
        id_item: "ID-3233",
        name_item: "Sticky notes",
        quantity: 5,
        status: "Claim has been requested by Amanda Davis",
        status_type: "Pending"
    },
    {
        id: 15,
        no: 15,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/150151/03.2023",
        requestor: "William Martinez",
        id_item: "ID-3435",
        name_item: "Glue",
        quantity: 1,
        status: "Claim has been requested by William Martinez",
        status_type: "Pending"
    },
    {
        id: 16,
        no: 16,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/159796/03.2023",
        requestor: "Sophia Jackson",
        id_item: "ID-3637",
        name_item: "Highlighter",
        quantity: 4,
        status: "Claim has been requested by Sophia Jackson",
        status_type: "Pending"
    },
    {
        id: 17,
        no: 17,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/169441/03.2023",
        requestor: "Daniel Wilson",
        id_item: "ID-3839",
        name_item: "Eraser",
        quantity: 3,
        status: "Claim has been requested by Daniel Wilson",
        status_type: "Pending"
    },
    {
        id: 18,
        no: 18,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/179086/03.2023",
        requestor: "Olivia Martin",
        id_item: "ID-4041",
        name_item: "Stapler",
        quantity: 1,
        status: "Claim has been requested by Olivia Martin",
        status_type: "Pending"
    },
    {
        id: 19,
        no: 19,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/188731/03.2023",
        requestor: "Ethan Clark",
        id_item: "ID-4243",
        name_item: "Binder clips",
        quantity: 2,
        status: "Claim has been requested by Ethan Clark",
        status_type: "Pending"
    },
    {
        id: 20,
        no: 20,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/198376/03.2023",
        requestor: "Isabella Adams",
        id_item: "ID-4445",
        name_item: "Hole punch",
        quantity: 1,
        status: "Claim has been requested by Isabella Adams",
        status_type: "Pending"
    },
    {
        id: 21,
        no: 21,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/208021/03.2023",
        requestor: "Mason Wright",
        id_item: "ID-4647",
        name_item: "Rubber bands",
        quantity: 4,
        status: "Claim has been requested by Mason Wright",
        status_type: "Pending"
    },
    {
        id: 22,
        no: 22,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/217666/03.2023",
        requestor: "Sofia Hernandez",
        id_item: "ID-4849",
        name_item: "Envelopes",
        quantity: 10,
        status: "Claim has been requested by Sofia Hernandez",
        status_type: "Pending"
    },
    {
        id: 23,
        no: 23,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/227311/03.2023",
        requestor: "Logan King",
        id_item: "ID-5051",
        name_item: "Markers",
        quantity: 6,
        status: "Claim has been requested by Logan King",
        status_type: "Pending"
    },
    {
        id: 24,
        no: 24,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/236956/03.2023",
        requestor: "Avery Garcia",
        id_item: "ID-5253",
        name_item: "Correction tape",
        quantity: 2,
        status: "Claim has been requested by Avery Garcia",
        status_type: "Pending"
    },
    {
        id: 25,
        no: 25,
        created_date: "06/05/2023",
        request_no: "TRV-ABM/246601/03.2023",
        requestor: "Evelyn Cooper",
        id_item: "ID-5455",
        name_item: "Scissors",
        quantity: 1,
        status: "Claim has been requested by Evelyn Cooper",
        status_type: "Pending"
    }
]

export default atkrequestdata

