const cadata = [
    {
        id: 1,
        no: 1,
        created_date: '2022-01-01',
        ca_no: 'CA001',
        name: 'Agus',
        type: 'Meals',
        total: 150000,
        status: 'Request Submit By (Agus)',
    },
    {
        id: 2,
        no: 2,
        created_date: '2022-01-05',
        ca_no: 'CA002',
        name: 'Budi',
        type: 'Meals',
        total: 250000,
        status: 'Request Submit By (Budi)',
    },
    {
        id: 3,
        no: 3,
        created_date: '2022-01-10',
        ca_no: 'CA003',
        name: 'Cahya',
        type: 'Meals',
        total: 350000,
        status: 'Request Submit By (Cahya)',
    },
    {
        id: 4,
        no: 4,
        created_date: '2022-01-15',
        ca_no: 'CA004',
        name: 'Dewi',
        type: 'Meals',
        total: 450000,
        status: 'Request Submit By (Dewi)',
    },
    {
        id: 5,
        no: 5,
        created_date: '2022-01-20',
        ca_no: 'CA005',
        name: 'Eka',
        type: 'Meals',
        total: 550000,
        status: 'Request Submit By (Eka)',
    },
    {
        id: 6,
        no: 6,
        created_date: '2022-01-25',
        ca_no: 'CA006',
        name: 'Fina',
        type: 'Transport',
        total: 650000,
        status: 'Request Submit By (Fina)',
    },
    {
        id: 7,
        no: 7,
        created_date: '2022-02-01',
        ca_no: 'CA007',
        name: 'Gita',
        type: 'Transport',
        total: 750000,
        status: 'Request Submit By (Gita)',
    },
    {
        id: 8,
        no: 8,
        created_date: '2022-02-05',
        ca_no: 'CA008',
        name: 'Hari',
        type: 'Transport',
        total: 850000,
        status: 'Request Submit By (Hari)',
    },
    {
        id: 9,
        no: 9,
        created_date: '2022-02-10',
        ca_no: 'CA009',
        name: 'Indra',
        type: 'Transport',
        total: 950000,
        status: 'Request Submit By (Indra)',
    },
    {
        id: 10,
        no: 10,
        created_date: '2022-02-15',
        ca_no: 'CA010',
        name: 'Jaka',
        type: 'Transport',
        total: 1050000,
        status: 'Request Submit By (Jaka)',
    },
    {
        id: 11,
        no: 11,
        created_date: '2022-02-20',
        ca_no: 'CA011',
        name: 'Kiki',
        type: 'Bensin',
        total: 1150000,
        status: 'Request Submit By (Kiki)',
    },
    {
        id: 12,
        no: 12,
        created_date: '2022-02-25',
        ca_no: 'CA012',
        name: 'Lina',
        type: 'Bensin',
        total: 1250000,
        status: 'Request Submit By (Lina)',
    },
    {
        id: 13,
        no: 13,
        created_date: '2022-03-01',
        ca_no: 'CA013',
        name: 'Mira',
        type: 'Bensin',
        total: 1350000,
        status: 'Request Submit By (Mira)',
    },
    {
        id: 14,
        no: 14,
        created_date: '2022-03-05',
        ca_no: 'CA014',
        name: 'Nana',
        type: 'Bensin',
        total: 1450000,
        status: 'Request Submit By (Nana)',
    },
    {
        id: 15,
        no: 15,
        created_date: '2022-03-10',
        ca_no: 'CA015',
        name: 'Omar',
        type: 'Bensin',
        total: 1550000,
        status: 'Request Submit By (Omar)',
    },
    {
        id: 16,
        no: 16,
        created_date: '2022-03-15',
        ca_no: 'CA016',
        name: 'Putri',
        type: 'Meals',
        total: 1650000,
        status: 'Request Submit By (Putri)',
    },
    {
        id: 17,
        no: 17,
        created_date: '2022-03-20',
        ca_no: 'CA017',
        name: 'Qori',
        type: 'Transport',
        total: 1750000,
        status: 'Request Submit By (Qori)',
    },
    {
        id: 18,
        no: 18,
        created_date: '2022-03-25',
        ca_no: 'CA018',
        name: 'Rika',
        type: 'Bensin',
        total: 1850000,
        status: 'Request Submit By (Rika)',
    },
    {
        id: 19,
        no: 19,
        created_date: '2022-04-01',
        ca_no: 'CA019',
        name: 'Siska',
        type: 'Bensin',
        total: 1950000,
        status: 'Request Submit By (Siska)',
    },
    {
        id: 20,
        no: 20,
        created_date: '2022-04-05',
        ca_no: 'CA020',
        name: 'Tono',
        type: 'Meals',
        total: 2050000,
        status: 'Request Submit By (Tono)',
    },
    {
        id: 21,
        no: 21,
        created_date: '2022-04-10',
        ca_no: 'CA021',
        name: 'Umar',
        type: 'Transport',
        total: 2250000,
        status: 'Request Submit By (Umar)',
    },
    {
        id: 22,
        no: 22,
        created_date: '2022-04-15',
        ca_no: 'CA022',
        name: 'Vina',
        type: 'Meals',
        total: 2350000,
        status: 'Request Submit By (Vina)',
    },
    {
        id: 23,
        no: 23,
        created_date: '2022-04-20',
        ca_no: 'CA023',
        name: 'Wati',
        type: 'Transport',
        total: 2450000,
        status: 'Request Submit By (Wati)',
    },
    {
        id: 24,
        no: 24,
        created_date: '2022-04-25',
        ca_no: 'CA024',
        name: 'Xander',
        type: 'Bensin',
        total: 2550000,
        status: 'Request Submit By (Xander)',
    },
    {
        id: 25,
        no: 25,
        created_date: '2022-04-30',
        ca_no: 'CA025',
        name: 'Yanti',
        type: 'Meals',
        total: 2650000,
        status: 'Request Submit By (Yanti)',
    },
];

export default cadata;